Change the default configuration to Seaport 1.4
ProjectOpenSea/seaport-js pull request #180
Opened 2023-03-09 20:58 UTC by JoshuaSchmidt-OpenSea

The API no longer accepts Seaport 1.4 so the default configuration should now be changed to use Seaport 1.4

2023-03-09 22:39 UTC, montasaurus approved these changes

2023-03-09 23:24 UTC, ryanio requested changes

2023-03-09 23:24 UTC, ryanio commented on package.json
> +  "version": "1.1.10",
Version would be 1.1.0

2023-03-10 05:31 UTC, ryanio approved these changes

2023-03-10 16:03 UTC, merged